name: Playwright Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**/README.md"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      testType:
        description: "Type of tests to run (ui, api, mobile, all)"
        required: false
        default: "all"

env:
  NODE_ENV: test
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: false
  TS_NODE_PROJECT: playwright.config.ts

jobs:
  test:
    name: Playwright Automation
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20]
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: ./
    continue-on-error: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Playwright Test Summary
        if: always()
        run: |
          if [ -f playwright-report/results.json ]; then
            jq '
              {
                project: (.suites[0].title // "N/A"),
                tests: [
                  .suites[]?.specs[]?.tests[]? | {name: .title, status: .outcome}
                ]
              }
            ' playwright-report/results.json > test-summary.json
          else
            echo '{"project":"N/A","tests":[]}' > test-summary.json
          fi

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: playwright-report-${{ matrix.node-version }}-${{ matrix.os }}
          path: playwright-report/

      - name: Upload Trace Files
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: traces-${{ matrix.node-version }}-${{ matrix.os }}
          path: test-results/

      - name: Slack Notification - Summary
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -s test-summary.json ]; then
            SUMMARY=$(jq -r '
              "Playwright Project: \(.project)\n" +
              "Tests:\n" +
              ([.tests[] | "- \(.name): \(.status)"] | join("\n")) + "\n\n" +
              "✅ Passed: \([.tests[] | select(.status=="expected")] | length)\n" +
              "❌ Failed: \([.tests[] | select(.status=="unexpected")] | length)\n" +
              "⏭️ Skipped: \([.tests[] | select(.status=="skipped")] | length)\n"
            ' test-summary.json)
          else
            SUMMARY="No test results found."
          fi
          curl -X POST -H 'Content-type: application/json' --data "{\"blocks\": [{\"type\": \"section\", \"text\": {\"type\": \"mrkdwn\", \"text\": \"*Playwright Test Summary*\n$SUMMARY\"}}]}" $SLACK_WEBHOOK_URL

      - name: Slack Notification - Success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✅ Playwright tests passed with Node.js *${{ matrix.node-version }}* on *${{ matrix.os }}*"}' $SLACK_WEBHOOK_URL

      - name: Slack Notification - Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"❌ Playwright tests failed with Node.js *${{ matrix.node-version }}* on *${{ matrix.os }}*"}' $SLACK_WEBHOOK_URL

      - name: Slack Notification - Cancelled
        if: cancelled()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ Playwright tests cancelled with Node.js *${{ matrix.node-version }}* on *${{ matrix.os }}*"}' $SLACK_WEBHOOK_URL
